name: NobilityRegions
version: 0.5
main: net.civex4.nobilityregions.NobilityRegions
commands:
  getregion:
    description: Displays the net.civex4.nobilityregions.region you are in
    usage: /getregion
    aliases: [nrgr]
  setregionname:
    description: Set the name of a net.civex4.nobilityregions.region (defaults to net.civex4.nobilityregions.region you are in)
    usage: /setregionname (name of net.civex4.nobilityregions.region to change)
    aliases: [nrsn]
  setregionhabitability:
    description: Set the habitability of a net.civex4.nobilityregions.region (defaults to net.civex4.nobilityregions.region you are in)
    usage: /setregionhabitability (name of net.civex4.nobilityregions.region to change) <true|false>
    aliases: [nrsh]
  setregionresource:
    description: Set a resource of a net.civex4.nobilityregions.region (defaults to the net.civex4.nobilityregions.region you are in)
    usage: /setregionresource (name of net.civex4.nobilityregions.region to add a resource to)
    aliases: [nrsr]
  listregions:
    description: (DEBUG) Lists all of the Regions
    usage: /listregions (world)
    aliases: [nrl]
  searchregions:
    description: (DEBUG) Searches all of the Regions for a matching name
    usage: /searchregions <query>
    aliases: [nrs]
  regioninfo:
    description: (DEBUG) Shows information about a specific net.civex4.nobilityregions.region
    usage: /regioninfo (name of net.civex4.nobilityregions.region)
    aliases: [nri]