name: NobilityRegions
version: ${project.version}
main: io.github.kingvictoria.NobilityRegions
depend: [NobilityItems]
api-version: 1.14
commands:
  nobilityregions:
    description: NobilityRegions commands
    usage: /nobilityregions (argument) ([other stuff...])
    aliases: [nr]