name: NobilityRegions
version: 0.4
main: io.github.kingvictoria.NobilityRegions
commands:
  getregion:
    description: Displays the region you are in
    usage: /getregion
  setregionname:
    description: Set the name of a region (defaults to region you are in)
    usage: /setregionname (name of region to change)
  setregionhabitability:
    description: Set the habitability of a region (defaults to region you are in)
    usage: /setregionhabitability (name of region to change) <true|false>
  listregions:
    description: (DEBUG) Lists all of the Regions
    usage: /listregions (world)
  searchregions:
    description: (DEBUG) Searches all of the Regions for a matching name
    usage: /searchregions <query>
  regioninfo:
    description: (DEBUG) Shows information about a specific region
    usage: /regioninfo <name>