name: NobilityRegions
version: 0.5
main: io.github.kingvictoria.NobilityRegions
api-version: 1.13
commands:
  getregion:
    description: Displays the region you are in
    usage: /getregion
    aliases: [nrgr]
  setregionname:
    description: Set the name of a region (defaults to region you are in)
    usage: /setregionname (name of region to change)
    aliases: [nrsn]
  setregionhabitability:
    description: Set the habitability of a region (defaults to region you are in)
    usage: /setregionhabitability (name of region to change) <true|false>
    aliases: [nrsh]
  setregionresource:
    description: Set a resource of a region (defaults to the region you are in)
    usage: /setregionresource (name of region to add a resource to)
    aliases: [nrsr]
  listregions:
    description: (DEBUG) Lists all of the Regions
    usage: /listregions (world)
    aliases: [nrl]
  searchregions:
    description: (DEBUG) Searches all of the Regions for a matching name
    usage: /searchregions <query>
    aliases: [nrs]
  regioninfo:
    description: (DEBUG) Shows information about a specific region
    usage: /regioninfo (name of region)
    aliases: [nri]